language: python
python:
    - 2.7
services: postgresql
env:
    - DJANGO=1.8
install:
    - pip install flake8 --quiet
    - pip install psycopg2 --quiet
    - pip install -q Django==$DJANGO --quiet
    - pip install pyunpack --quiet
before_script:
    - psql -c "CREATE DATABASE testdb;" -U postgres
script:
    - flake8 .

    - python manage.py migrate auth
    - python manage.py makemigrations Athena
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test
